# Generated by Django 3.0.4 on 2020-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
